export const DOMAINS = [
  "Software Engineering",
  "Data Science",
  "Cybersecurity",
  "Graphic Design",
  "Digital Marketing",
  "Product Management",
  "Project Management",
  "Finance",
  "Accounting",
  "Human Resources",
  "Education",
  "Healthcare",
  "Legal",
  "Mechanical Engineering",
  "Civil Engineering",
  "Electrical Engineering",
  "Biotechnology",
  "Psychology",
  "Architecture",
  "Environmental Science",
  "Sales",
  "Customer Service",
  "Writing & Editing",
  "Translation",
  "Music Production",
  "Film & Video Production",
  "Game Development",
  "UX/UI Design",
  "Artificial Intelligence",
  "Machine Learning",
];
